### ISSUE TITLE
No release for commit ref: 93ecc27

### ISSUE THREAD

**Issue by thundergolfer** [rspec/rspec-autotest#30]
## Description 

Could the distribution of this gem on https://rubygems.org/ be updated? 

By using commit `93ecc27` I was able to this gem working properly with Rails 5 and RSpec 3. Using the latest rubygems.org release (1.0.0), I got: 

```
NameError: uninitialized constant ActiveSupport::Autoload
  /bundle/gems/activesupport-5.1.4/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>'
  /bundle/gems/activesupport-5.1.4/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
  /bundle/gems/activesupport-5.1.4/lib/active_support/number_helper.rb:1:in `<top (required)>'
  /bundle/gems/activesupport-5.1.4/lib/active_support/core_ext/numeric/conversions.rb:2:in `require'
  /bundle/gems/activesupport-5.1.4/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
  /bundle/gems/activesupport-5.1.4/lib/active_support/core_ext/numeric.rb:4:in `require'
  /bundle/gems/activesupport-5.1.4/lib/active_support/core_ext/numeric.rb:4:in `<top (required)>'
  /bundle/gems/activesupport-5.1.4/lib/active_support/core_ext.rb:2:in `require'
  /bundle/gems/activesupport-5.1.4/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
  /bundle/gems/activesupport-5.1.4/lib/active_support/core_ext.rb:1:in `each'
  /bundle/gems/activesupport-5.1.4/lib/active_support/core_ext.rb:1:in `<top (required)>'
  /bundle/gems/rspec-autotest-1.0.0/lib/rspec/rails/autotest.rb:25:in `require'
  /bundle/gems/rspec-autotest-1.0.0/lib/rspec/rails/autotest.rb:25:in `<top (required)>'
  /bundle/gems/rspec-autotest-1.0.0/lib/autotest/rails_rspec.rb:1:in `require'
  /bundle/gems/rspec-autotest-1.0.0/lib/autotest/rails_rspec.rb:1:in `<top (required)>'
  /app/.autotest:2:in `require'
  /app/.autotest:2:in `<top (required)>'
  /bundle/gems/ZenTest-4.11.1/lib/autotest.rb:323:in `load'
  /bundle/gems/ZenTest-4.11.1/lib/autotest.rb:323:in `block in initialize'
  /bundle/gems/ZenTest-4.11.1/lib/autotest.rb:322:in `each'
  /bundle/gems/ZenTest-4.11.1/lib/autotest.rb:322:in `initialize'
  /bundle/gems/autotest-rails-4.2.1/lib/autotest/rails.rb:7:in `initialize'
  /bundle/gems/ZenTest-4.11.1/lib/autotest.rb:248:in `new'
  /bundle/gems/ZenTest-4.11.1/lib/autotest.rb:248:in `run'
  /bundle/gems/ZenTest-4.11.1/bin/autotest:6:in `<top (required)>'
  /bundle/bin/autotest:23:in `load'
  /bundle/bin/autotest:23:in `<top (required)>'
```

**Comment by JonRowe** [comment]
Hm, odd, we have 1.0.1 but for some reason its not on rubygems

**Comment by JonRowe** [comment]
1.0.1 has now been released, commits since are just for CI and not necessary for a release.

**Comment by thundergolfer** [comment]
Hey @JonRowe, thanks for your response. 

> commits since are just for CI and not necessary for a release.

I am pretty sure this commit, https://github.com/rspec/rspec-autotest/commit/4d0ce08c8c94384c11ddc671cd520d8134d2e44c,  is what fixes my current issues with `rspec-autotest`, and it's not in release `1.0.1`.

**Comment by JonRowe** [comment]
My apologies, `1.0.2` has now been released.

**Comment by thundergolfer** [comment]
🎉 Sweet, thanks for your help. Happy to close this issue now.
